# Generated by Django 5.2.8 on 2025-12-05 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('es_rotativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAsistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CHECK_IN', 'Entrada'), ('CHECK_OUT', 'Salida'), ('PAUSA_IN', 'Inicio Pausa'), ('PAUSA_OUT', 'Fin Pausa')], max_length=20)),
                ('registrado_el', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_hora_dispositivo', models.DateTimeField(help_text='Hora enviada por el celular/web')),
                ('fuente', models.CharField(choices=[('APP', 'Aplicación Móvil'), ('WEB', 'Plataforma Web'), ('LECTOR', 'Lector Biométrico/Físico')], default='APP', max_length=20)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('dentro_geocerca', models.BooleanField(default=False)),
                ('foto_url', models.ImageField(blank=True, null=True, upload_to='asistencia_evidence/')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-registrado_el'],
            },
        ),
        migrations.CreateModel(
            name='Geocerca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CIRCULO', 'Circular (Radio)'), ('POLIGONO', 'Polígono')], default='CIRCULO', max_length=20)),
                ('coordenadas', models.JSONField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JornadaCalculada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True)),
                ('hora_primera_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_ultima_salida', models.DateTimeField(blank=True, null=True)),
                ('minutos_trabajados', models.IntegerField(default=0)),
                ('minutos_tardanza', models.IntegerField(default=0)),
                ('minutos_extra', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('COMPLETO', 'Completo'), ('INCOMPLETO', 'Incompleto'), ('SIN_REGISTROS', 'Sin Registros'), ('AUSENTE', 'Ausente')], default='SIN_REGISTROS', max_length=20)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de días: 1=Lunes, 7=Domingo')),
                ('tolerancia_minutos', models.PositiveIntegerField(default=5)),
                ('requiere_gps', models.BooleanField(default=True)),
                ('requiere_foto', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
