# Generated by Django 6.0.1 on 2026-01-17 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionturno',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='asignacionturno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='eventoasistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='eventoasistencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='geocerca',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geocercas', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='jornadacalculada',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='jornadacalculada',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='turno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='asignacionturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.turno'),
        ),
        migrations.AddIndex(
            model_name='eventoasistencia',
            index=models.Index(fields=['empresa', 'registrado_el'], name='attendance__empresa_b58464_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jornadacalculada',
            unique_together={('empleado', 'fecha')},
        ),
        migrations.AlterUniqueTogether(
            name='asignacionturno',
            unique_together={('empleado', 'fecha_inicio')},
        ),
    ]
