# Generated by Django 6.0.1 on 2026-01-17 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(help_text='Ej: CREAR_EMPRESA, EDITAR_EMPRESA, CREAR_CATALOGO', max_length=100)),
                ('entidad', models.CharField(help_text='Ej: Empresa, CatalogoGlobal', max_length=100)),
                ('entidad_id', models.UUIDField()),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('SEDE', 'Sede'), ('AREA', 'Área'), ('DEPTO', 'Departamento')], max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoGlobal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PAIS', 'País'), ('MONEDA', 'Moneda')], max_length=20)),
                ('codigo', models.CharField(help_text='Ej: USD, EC', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('tipo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('nombre_comercial', models.CharField(max_length=150)),
                ('ruc_nit', models.CharField(max_length=20, verbose_name='RUC/NIT')),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('moneda', models.ForeignKey(limit_choices_to={'tipo': 'MONEDA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_moneda', to='core.catalogoglobal')),
                ('pais', models.ForeignKey(limit_choices_to={'tipo': 'PAIS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_pais', to='core.catalogoglobal')),
            ],
            options={
                'ordering': ['nombre_comercial'],
            },
        ),
    ]
