# Generated by Django 6.0.1 on 2026-01-17 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puesto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.empresa'),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_unidades', to='core.unidadorganizacional'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos_asignados', to='core.unidadorganizacional'),
        ),
        migrations.AddIndex(
            model_name='unidadorganizacional',
            index=models.Index(fields=['empresa', 'estado'], name='core_unidad_empresa_192f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='puesto',
            index=models.Index(fields=['empresa'], name='core_puesto_empresa_af8290_idx'),
        ),
    ]
