# Generated by Django 6.0.1 on 2026-01-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_direccion_empresa_email_empresa_sitio_web_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
