# Generated by Django 5.2.8 on 2025-12-05 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('documento', models.CharField(db_index=True, help_text='Cédula, DNI o Pasaporte', max_length=20)),
                ('email', models.EmailField(help_text='Correo corporativo o personal principal', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(help_text='Fecha de inicio de labores')),
                ('foto_url', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('BAJA', 'Baja')], default='ACTIVO', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='employees.empleado')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_puesto', to='core.puesto')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_unidad', to='core.unidadorganizacional')),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('empresa', 'documento')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato Firmado'), ('ANEXO', 'Anexo / Adenda'), ('CERTIFICADO', 'Certificado Médico/Estudios'), ('OTRO', 'Otro Documento')], max_length=20)),
                ('archivo_url', models.FileField(upload_to='expedientes_empleados/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cargado_el', models.DateTimeField(auto_now_add=True)),
                ('vigente', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='employees.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO', 'Plazo Fijo'), ('TEMPORAL', 'Temporal / Eventual'), ('PRACTICANTE', 'Practicante / Pasante')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('jornada_semanal_horas', models.PositiveIntegerField(default=40)),
                ('estado', models.BooleanField(default=True, help_text='Contrato vigente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('turno_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_asociados', to='attendance.turno')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='employees.empleado')),
            ],
        ),
    ]
