# Generated by Django 6.0.1 on 2026-01-18 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='asignado_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='employees.empleado'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
    ]
