# Generated by Django 6.0.1 on 2026-01-17 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAusencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('afecta_sueldo', models.BooleanField(default=False)),
                ('requiere_soporte', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_solicitados', models.PositiveIntegerField(default=1)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('adjunto_url', models.FileField(blank=True, null=True, upload_to='ausencias_soportes/')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to='employees.empleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='employees.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('tipo_ausencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaves.tipoausencia')),
            ],
        ),
        migrations.CreateModel(
            name='SaldoVacaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(help_text='Ej: 2025', max_length=4)),
                ('dias_asignados', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('dias_tomados', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_vacaciones', to='employees.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'unique_together': {('empleado', 'periodo')},
            },
        ),
    ]
