# Generated by Django 5.2.8 on 2025-12-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('AUTO', 'Auto'), ('MANAGER', 'Manager'), ('360', '360')], max_length=20)),
                ('instrumento', models.JSONField(default=dict)),
                ('puntaje_total', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='employees.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_hechas', to='employees.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(choices=[('%', '%'), ('PUNTOS', 'Puntos'), ('MINUTOS', 'Minutos'), ('HORAS', 'Horas')], max_length=20)),
                ('origen_datos', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('EVALUACION', 'Evaluación'), ('MIXTO', 'Mixto')], max_length=20)),
                ('formula', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('aplica_a', models.CharField(choices=[('PUESTO', 'Puesto'), ('UNIDAD', 'Unidad'), ('EMPLEADO', 'Empleado')], max_length=20)),
                ('objetivos', models.JSONField(default=list)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField()),
                ('hasta', models.DateField(blank=True, null=True)),
                ('ajustes_personalizados', models.JSONField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('plantilla_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.plantillakpi')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoKpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cumplimiento_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clasificacion', models.CharField(choices=[('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('ROJO', 'Rojo')], max_length=20)),
                ('calculado_el', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.kpi')),
            ],
        ),
    ]
